# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raghav', '0006_auto_20160219_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('stype', models.CharField(max_length=10)),
                ('alias', models.CharField(max_length=10)),
                ('update_in', models.IntegerField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_date', models.DateField()),
            ],
        ),
    ]
