# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raghav', '0008_emails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emails',
            new_name='Email',
        ),
    ]
