# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raghav', '0011_bibliographicdata_citiations_designatedstates_documents_eventhistory_familymember_fees_main_parentco'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('stype', models.CharField(max_length=10)),
                ('alias', models.CharField(max_length=10)),
            ],
        ),
    ]
